### ISSUE TITLE
Using `hadm_id` as the unique identifier

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/trauma-team-international#15]
For the `analysis` table, we must use an approach where `hadm_id` is unique, which means that if single `hadm_id` has more than one `icustay_id` we randomly pick one.

**Comment by pdey** [comment]
what about keeping all the `icustay_id` and and adding an `icustay_time` , instead of picking a random one. This serves two purposes -
1. analysis phase can choose which specific icu stay they want to look into
2. random pick may change when a VIEW is dropped and recreated, which may be not desirable if we want to tally analysis done before and after the update.

**Comment by mikkokotila** [comment]
Let's do last `icustay_id` per `hadm_id`.
